model:
  name: neural_ode
  params:
    vector_field:
      name: mlp
      params:
        hidden_dims: [64, 64]
        activation: tanh
    time_dependence: True
    time_length: 1.0
    time_steps: 10
    solver_params:
      atol: 1.4e-8
      rtol: 1.4e-8
    
optimizer:
  name: adam
  params:
    learning_rate: 5e-3

loss:
  name: ssiKLdiv
  params: {}

training:
  epochs: 100